# An action for locating known objects

# GOAL ======================================================

# Name of the object we are trying to find at this instance
string desired_object_name

# Names of all the objects expected in the scene, 
# including the previous 'desired_object_name' object
string[] expected_objects_names

# Current pose of the camera that is to remain fixed until result returned
#geometry_msgs/Pose camera_pose

# Region of interest - coordinates of bin
string bin_name
geometry_msgs/Pose front_bottom_right
geometry_msgs/Pose back_top_left

---
# RESULT ====================================================

# If the camera angle was bad or some other failure, return false
bool succeeded

# Array of found objects
FoundObject[] found_objects

---
# FEEDBACK ==================================================

# Value between 0 and 100. If not feedback is recieved after a certain
# period of time the pipeline will skip this product
float32 percent_complete
